// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8X6XSaui18s6DJMf9BGfAZ9Qplme5Ns',
    appId: '1:479589645448:web:29fad93a28d5c4524d733d',
    messagingSenderId: '479589645448',
    projectId: 'imic-fac14',
    authDomain: 'imic-fac14.firebaseapp.com',
    storageBucket: 'imic-fac14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0y8nQYJbdCbjywy-u1IaInmSCAq9GWk',
    appId: '1:479589645448:android:91ee8389334410124d733d',
    messagingSenderId: '479589645448',
    projectId: 'imic-fac14',
    storageBucket: 'imic-fac14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3cbNkNIzCKWu-nskxa5EnZPtrzzhBh4',
    appId: '1:479589645448:ios:6f3e07b4a04c235c4d733d',
    messagingSenderId: '479589645448',
    projectId: 'imic-fac14',
    storageBucket: 'imic-fac14.firebasestorage.app',
    iosBundleId: 'com.text1.imic',
  );
}
