// Track view model - for Firebase integration, use TrackService directly
import 'package:provide/model/mytrackmodel.dart';

class MyTracksViewController {
  final List<MyTrack> mytracks = [
    MyTrack(
      id: '1',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 1)),
      updatedAt: DateTime.now().subtract(Duration(days: 1)),
    ),
    MyTrack(
      id: '2',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 2)),
      updatedAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    MyTrack(
      id: '3',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 3)),
      updatedAt: DateTime.now().subtract(Duration(days: 3)),
    ),
    MyTrack(
      id: '4',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 4)),
      updatedAt: DateTime.now().subtract(Duration(days: 4)),
    ),
    MyTrack(
      id: '5',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 5)),
      updatedAt: DateTime.now().subtract(Duration(days: 5)),
    ),
    MyTrack(
      id: '6',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 6)),
      updatedAt: DateTime.now().subtract(Duration(days: 6)),
    ),
    MyTrack(
      id: '7',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 7)),
      updatedAt: DateTime.now().subtract(Duration(days: 7)),
    ),
    MyTrack(
      id: '8',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 8)),
      updatedAt: DateTime.now().subtract(Duration(days: 8)),
    ),
    MyTrack(
      id: '9',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 9)),
      updatedAt: DateTime.now().subtract(Duration(days: 9)),
    ),
    MyTrack(
      id: '10',
      userId: 'demo_user',
      title: "No Sleep Tonight",
      artist: "Young Blaze",
      producer: "Khaled",
      imageAsset: "assets/icons/component_1_1.png",
      duration: const Duration(minutes: 3, seconds: 45),
      createdAt: DateTime.now().subtract(Duration(days: 10)),
      updatedAt: DateTime.now().subtract(Duration(days: 10)),
    ),
  ];
}
